---
title: " Make nice tables"
output: 
  distill::distill_article:
    toc: true
    toc_float: true
---

Try to make the table that is already included in your document more beautiful.

My tip is to first save the table in a variable. Then you can pass this 
variable into the table functions:

```{r eval=FALSE, echo=TRUE}
penguins_sum <- penguins %>%
  filter(!(is.na(sex))) %>%
  group_by(species, sex) %>%
  summarize(
    bill_length = mean(bill_length_mm, na.rm = TRUE),
    bill_depth = mean(bill_depth_mm, na.rm = TRUE),
    flipper_length = mean(flipper_length_mm, na.rm = TRUE),
    body_mass = mean(body_mass_g, na.rm = TRUE)
  )
penguins_sum
```

### 2.1 Basic styling with `kable`

Start with the `kable` function. Before you use it, load the `knitr` package 
in the setup chunk.

You can for example:

- Add a caption
- Restrict the number of digits printed
- Change the column headers
- Change the alignment of text in the cells
- Use `booktabs` option (only works in PDF output, is ignored for HTML and Word output)

Knit the document in your target output format and see how the table looks like.

### 2.2 Advanced styling with `kableExtra` or `flextable`

Chose one of the options below depending on your priority output format and interest.
I recommend option 1, but if your focus is strongly on word documents, you can also 
choose option 2.

#### Option 1 `kableExtra` (PDF and HTML)

Don't forget to load the `kableExtra` package in the setup chunk.

Start adding extra styling to the table. For example, you can

- Apply some `kable_styling`, e.g
  - Font size
  - Position of the table or full width table
  - Specify `latex_options` and/or `bootstrap_options`
- Change the table theme using one of the `kable_*` themes (only HTML)
- Try packing some rows or columns together
- ...

Have a look at `?kable_styling` for more options.

If you still have time, have a look at the package documentation of `kableExtra`
for [PDF tables](https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf) or [HTML tables](https://haozhu233.github.io/kableExtra/awesome_table_in_html.html) to find many more options and examples.

#### Option 2 `flextable`

Don't forget to load the `flextable` package in the setup chunk.

Start by setting the default flex table options in the setup chunk.

- Have a look at the example on the slide and check out `?flextable::set_flextable_defaults`

Now print the table in your document as a flextable by passing it into the `flextable()` function.

Customize the look further, e.g. by

- Changing the header labels
- Adding a table caption
- Applying the formatting for the double columns

If you still have time, move from Word to HTML or PDF output and try the other packages.